# Generated by Django 3.1.3 on 2021-02-15 21:33

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='file',
            field=models.ImageField(default='ig-default-user.png', upload_to=apps.users.models.path),
        ),
    ]
