# Generated by Django 3.1.3 on 2021-02-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
    ]
